### ISSUE TITLE
license for Augusta proper (and perhaps Dragon and Tiger too, if different license)

### ISSUE THREAD

**Issue by optikos** [pchapin/augusta#1]
As mentioned in recent days over at comp.lang.ada, please overtly declare which license Augusta proper (and Dragon proper and Tiger, if differently-licensed) is distributed publicly here at GitHub.  As a library utilized by Dragon, SLEM appears to naturally to continue to be LGPL, extrapolating its ancestry from Timothy Morton.  The files that are derived works of OpenWatcom in WAC are licensed via Sybase OpenWatcom License, but is all of WAC (and perhaps all of Augusta proper?) to be licensed under Sybase OpenWatcom License?

Without an overt license-to-copy stated in writing here within or with this source code here at GitHub, various legal jurisdictions throughout the world may have different interpretations of your right-to-copy intent.  For example, as I understand it:  most of the world in the Berne Convention and WIPO nations, will default to strictly all rights reserved (i.e., no right to copy granted to anyone other than Peter Chapin), even without those magic words of “All rights reserved” in each file.  Other nations might default to public domain.  I suspect that neither of which is what you intend.

Portions of the Ada community would very much appreciate Augusta having a permissive nonGPL license, such as Apache2.0, BSD, Sybase OpenWatcom License, or similar.  We already have one incumbent Ada compiler that is strict GPL, which is causing atypical-for-GPL trouble for certain users of that compiler.  Additionally we already have an FSF (seeming-)twin of that incumbent that is GPL-with-RuntimeLibraryException, but there exists some suspicion that the twin variants of that compiler never reach identical content/bug-fixes, so one of those twins is suspected (by some portions of the Ada community) for years of being perpetually buggier than the other.  Portions of the Ada community would like to free ourselves of that never-congruent situation via a different permissively-licensed Ada2012/Ada2020 compiler without such complications.

**Comment by pchapin** [comment]
I removed SLEM and WAC from this repository. I couldn't contact the SLEM author to see if he would be open to a possible change in license, and WAC was going nowhere. Without these encumbrances, I applied an Apache 2.0 license to the remaining code base.

I'm about to significantly reorganize this repository to prepare it for future development when I retire (end of 2025). I will update the README in a few days with more details.
